### ISSUE TITLE
No matching activities found

### ISSUE THREAD

**Issue by Kkevsterrr** [NathanBaulch/rainbow-roads#1]
Super cool looking project! I was playing around with this, but I seem to get "No matching activities found" from line 316 in main.go. I think there might be an issue with the bounded_by flag. I believe the issue is with the `km` specified in the example - it works correctly if i just specify `5000` instead of `5km`. I've been able to work around it and I love the tool - thanks!

**Comment by NathanBaulch** [comment]
Weird, I use `5km` in my tests. Can you share the full command line?

**Comment by Kkevsterrr** [comment]
I must've done something wrong - I rebuilt it and the `km` seems to work now. Must've had some other typo - sorry to bother. Thanks again for the great tool!
