### ISSUE TITLE
panic: image: NewPaletted Rectangle has huge or negative dimensions

### ISSUE THREAD

**Issue by rasher** [NathanBaulch/rainbow-roads#2]
There seems to be an issue with `geo#mercatorMeters` which can return NaN for `y` (if `math.Tan(lat+(math.Pi/4))` is negative).

I'm thinking it could be related to my location in the world (Denmark) relative to you (something to do with negative/positive lat/lon?), but the math is no fun so I gave up digging any further.

Github seemingly won't let me attach files unfortunately (tried everything!). If you want an example activity chuck me an email. Gmail with same username as github.

**Comment by brandonpollack23** [comment]
Have the same issue, live in seattle, figure it's probably the same issue

**Comment by matjazl3** [comment]
Have the same issue for files located in Slovenia. Like @rasher already investigated, `geo#mercatorMeters` returns NaN for certain values.

Replacing the function with a common latLonToMeteres fixes the problem:
`func mercatorMeters(lat, lon float64) (float64, float64) {
	x := lon * 2 * math.Pi * 6378137 / 2 / 180
	y := math.Log(math.Tan((90+lat)*math.Pi/360)) / (math.Pi / 180)
	y = y * 2 * math.Pi * 6378137 / 2 / 180
	return x, y
}`

The function implementation I used is based on https://github.com/davvo/mercator

**Comment by NathanBaulch** [comment]
Thanks all, fixed in v0.1.1! Just a silly trig bug that only affected people outside of ±45 latitude, oops.
