### ISSUE TITLE
Request: Support gzipped activities

### ISSUE THREAD

**Issue by rasher** [NathanBaulch/rainbow-roads#5]
Strava exports deliver activities gzipped, so it would be helpful if gzipped files was supported.

The structure is:

```
export_<user_id>.zip/
  activities/
    <act_id>.gpx.gz
    <act_id>.tcx.gz
    <act_id>.fit.gz
```

**Comment by NathanBaulch** [comment]
Excellent, I was hoping someone would test against a Strava export.
I've added support for this, let me know how you go.

**Comment by rasher** [comment]
Looks like it's working as far as my original request goes ✔️

There's a practical issue with Strava exports. Namely that they include routes (gpx) made on the platform as well. To expand the structure:
```
export_<user_id>.zip/
  activities/
    <act_id>.gpx.gz
    <act_id>.tcx.gz
    <act_id>.fit.gz
  routes/
    <id>.gpx
```

Ideas to make it easier to work with Strava exports:
- Allow path indexing into zip files. Something like `path/to/export_1234.zip:activities`
- Skip route gpx files. At least for the ones I'm seeing from Strava, there are no timestamps in the trkpt elements. So the entire track just flashes at the start of the animation.
- Have an "ignore pattern" option that lets you ignore files based on path/filename (so something like `-ignore_files "routes/*.gpx"`)

**Comment by GSLaaitie** [comment]
I'm so glad to see this is getting Strava support.
I'm a complete newbie but was able to run the code on my Strava export. In my export zip file there are 695 *.fit.gz files and 3 *.GPX files.
When I run the code, it only recognizes 3 activity files. Any idea how to make it see the *.fit.gz files too?

**Comment by NathanBaulch** [comment]
@rasher I agree options 1 and 3 would be useful but for now option 2 is the easiest. Done!

@GSLaaitie What version are you running? There hasn't been a binary release since gzip support was added.

**Comment by GSLaaitie** [comment]
> @GSLaaitie What version are you running? There hasn't been a binary release since gzip support was added.

Ah okay that makes sense. I just installed it using Go on the CLI. I'll just have to wait for the new release?

**Comment by NathanBaulch** [comment]
You can grab the latest unreleased development version at any time by re-running the install command with the main branch specified. That should fix your issue @GSLaaitie.

```
go install github.com/NathanBaulch/rainbow-roads@main
````
