### ISSUE TITLE
Random starting points Using Strava data

### ISSUE THREAD

**Issue by GSLaaitie** [NathanBaulch/rainbow-roads#9]
Hi and thanks for making this tool available

I'm using Strava data with the latest version (v0.2.1)
About 98% of my runs start at home. However, the first frame of my .gif has the runs starting all over the route. See the attached pic for the first frame. On this pic you are able to make out the routes, so it is the timing or something that must be out. My expectation is that all the bright dots should start at the same place for the first frame. Any ideas?
![image](https://user-images.githubusercontent.com/69239319/158562699-c85b0a41-aeac-4f66-94f9-e2c1941caac6.png)

**Comment by NathanBaulch** [comment]
How peculiar! Would you be willing to share your data with me somehow?

**Comment by GSLaaitie** [comment]
Yes, no problem. How should I send it to you?

**Comment by NathanBaulch** [comment]
Probably easiest if you send me a shared file link (Dropbox, GDrive, OneDrive, iCloud, etc) via Reddit DM. Alternatively you can email it to my username at gmail dot com.

**Comment by GSLaaitie** [comment]
Thanks. Just sent you a link on Reddit

**Comment by NathanBaulch** [comment]
Fixed. This is the first time I've seen laps used in TCX files so all your 1km segments were being animated in parallel. These are now stitched together as you'd expect.
I've just released v0.2.1 with this fix, thanks!

**Comment by GSLaaitie** [comment]
It works now. Thanks!!!
